on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: develop
    steps:
      - run: echo "Deploy"
